<hr>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; SpedEX <?php echo date('Y');?></p>
        </div>
    </div>
</footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAs3u-T_zmb4i9tnHPB0tieI2icQ5A3nkQ"
        type="text/javascript"></script>

<script>
    function initialize()
    {
        var check = document.getElementById("map");

        if(check){
            var myLatLng = new google.maps.LatLng(47.654077,19.277937);
            var map = new google.maps.Map(check,
                {
                    zoom: 17,
                    center: myLatLng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });

            var marker = new google.maps.Marker(
                {
                    position: myLatLng,
                    map: map,
                    title: 'Rajya Sabha'
                });
        }

    }
</script>

</body>

</html>