<!-- Header Carousel -->
<?php include "public/views/partials/slider.phtml";?>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Expressz fuvarozás
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <span>
                <p>Export, import, rész, komplett rakományokat szállítunk Európa bármelyik pontjára, veresegyházi indulással, a lehetőségekhez mérten a legrövidebb tranzitidőkkel.</p>
                <p>Az expressz szállítást dobozos furgonjaink segítségével végezzük az EU-n belül. Árufelvételtől számított 24 órán belül a lerakón van az áruja. Nem csak komplett rakományokra vállalunk ilyen rövid határidőket, hanem kisebb részrakományokra is. Fuvarmegrendeléstől azonnal ki tudjuk állítani a furgont a felrakóra.</p>
                <p>A furgontól nagyobb mennyiségű rakományokat 7,5to 12to 40to tehergépjárművekkel, alválallkozókkal teljesítjük.</p>
                <p>Függetlenül a célállomástól és rakomány mérettől, cégünk expressz szállítása révén gyorsan és biztonságosan juttatja csomagját a megjelölt helyre. </p>
                <p>Árajánlatot 1 órán belül küldünk Önöknek. Várjuk árajánlatkérésüket expressz szállítással vagy bármilyen belföldi árufuvarozással vagy külföldi fuvarfeladattal kapcsolatban. </p>
                <br/>
                <p>Megbízóink részére, alapszolgáltatásként GPS nyomkövetést tudunk biztosítani.</p>
            </span>
        </div>
    </div>