<!-- Header Carousel -->
<?php include "public/views/partials/slider.phtml";?>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Üdvözöljük honlapunkon!
            </h1>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> Expressz szállítmányozás</h4>
                </div>
                <div class="panel-body">
                    <p>
                        Megrendelőink kívánsága szerint az EU területén belül bármilyen árut eljuttatunk rendeltetési helyére a kiscsomagtól a komplett kamion mennyiségig rövid határidővel.
                    </p>
                    <a href="/express" class="btn btn-default">Tovább</a>
                </div>
            </div>
        </div>
     <!--   <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-gift"></i> Gyüjtő fuvarozás</h4>
                </div>
                <div class="panel-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                    <a href="/gyujto" class="btn btn-default">Tovább</a>
                </div>
            </div>
        </div>-->
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-compass"></i>Kapcsolat</h4>
                </div>
                <div class="panel-body">
                    <p>Telefonos ügyfélszolgálatunk a nap 24 órájában a megbízóink rendelkezésére áll.</p>
                    <a href="/kapcsolat" class="btn btn-default">Tovább</a>
                </div>
            </div>
        </div>
    </div>
    <div id="title" style="visibility: hidden;">Főoldal</div>