<!-- Header Carousel -->
<?php include "public/views/partials/slider.phtml";?>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Kapcsolat
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <span>
                <h3>Fuvarszervezés,Ügyfélszolgálat:</h3>
                <b>Csizmadia István	</b>
                <p>+36 30 670 1376</p>
                <p>istvan@spedextrans.com</p>
                <br/>
                <h3>HR ügyintézés:</h3>
                <b>Kardos Enikő</b>
                <p>info@spedextrans.com</p>
            </span>
        </div>
        <div class="col-lg-6">
            <div id="map" style="width: 100%; height: 300px"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <a href="mailto:info@spedextrans.com&subject=Ajánlatkérés">Kérj ajánlatot emailben</a>
        </div>
    </div>
    <div id="title" style="visibility: hidden;">Kapcsolat</div>